### ISSUE TITLE
Mejora: manejo de errores

### ISSUE THREAD

**Issue by carlosE17** [ericknavarro/InterpreteSencilloIronyCS#1]
actualmente el proyecto 'crashea/truena' (no se ejecuta) al encontrar el primer error sintactico, por lo cual mi propuesta es ejecutar solamente cuando la entrada no tenga ningun error, de lo contrario generar un reporte (tabla en html) el cual enliste todos los errores encontrados, y de esta forma evitar que el proyecto ejecute codigo erroneo, ademas de facilitar a cualquier usuario el uso de este proyecto en caso desee modificar la entrada del mismo.

Carlos R. Estrada N.  -->201700314

**Comment by rjanixz** [comment]
Muy buena idea @carlosE17  , no olvides realizar el pull request con la propuesta de código respectivo.

**Comment by ericknavarro** [comment]
PR: https://github.com/ericknavarro/InterpreteSencilloIronyCS/pull/12

**Comment by rjanixz** [comment]
@carlosE17 buen trabajo. Mandame un correo con tus datos: carnet, nombre, usuario de github, repositorio, sección, número de issue, y número de pull request para control de tu nota.
