### ISSUE TITLE
Nuevas operaciones (++, --, &&, ||)

### ISSUE THREAD

**Issue by 201314164** [ericknavarro/InterpreteSencilloIronyCS#2]
Se implementarán las siguientes operaciónes para expandir la funcionalidad del analizador: 

- Aumento( ++ ) esto para reemplazar a "a= a+1".
-Decremento( -- ) 
-Operador lógico AND( && ) 
-Operador Lógico OR( || ) 

Oswaldo Giovanni Cáceres Samayoa - 201314164

**Comment by rjanixz** [comment]
Muy buena idea @201314164 , no olvides realizar el pull request con la propuesta de código respectivo.

**Comment by ericknavarro** [comment]
Se cierra el issue luego de haber aprobado el pull request
