### ISSUE TITLE
Mejora: Interfaz gráfica

### ISSUE THREAD

**Issue by Luiskr1993** [ericknavarro/InterpreteSencilloIronyCS#3]
Se implementará una interfaz que contenga un área específica para editar código o cargar el contenido de algún archivo de texto. Esto con la finalidad de poder agregar más líneas de código o escribir nuevos casos de prueba. También se agregará una sección de 'consola', en la cual se puedan mostrar algunos mensajes de los procesos que se vayan ejecutando, y los errores producidos en tiempo de ejecución. 

Luis Carlos Valiente Salazar - 201122864

**Comment by rjanixz** [comment]
Muy buena idea @Luiskr1993 , no olvides realizar el pull request con la propuesta de código respectivo.

-

**Comment by ericknavarro** [comment]
PR: https://github.com/ericknavarro/InterpreteSencilloIronyCS/pull/11

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte Luis Carlos.

Saludos cordiales.
