### ISSUE TITLE
Error en comentario: Linea 16

### ISSUE THREAD

**Issue by HPecene** [ericknavarro/InterpreteSencilloIronyCS#4]
Tras leer todo el archivo de entrada en la linea 16 esta escrito:
"//Se asigna a la variable c el valor 0"
Pero en la linea 17 esta:
"c=1;"
El comentario es erroneo y al cambiar el valor de c a 0 como dice el comentario solo se muestran 4 tablas no las 5 que se desean mostrar.
El unico cambio para ese error seria cambiar el comentario.

Jose Andres Morales Calderon - 201602754

**Comment by rjanixz** [comment]
Excelente observación @HPecene, no olvides realizar el pull request con los cambios de código respectivos.

**Comment by ericknavarro** [comment]
Muchas gracias por la observación José, en respuesta a la misma, se hizo el siguiente commit: 
https://github.com/ericknavarro/InterpreteSencilloIronyCS/commit/1835aef8c2b3ba5338feff74c8198a98deba4799
