### ISSUE TITLE
Mejora en el resultado final despues de las tablas

### ISSUE THREAD

**Issue by HPecene** [ericknavarro/InterpreteSencilloIronyCS#5]
Cuando se dan los resultados despues de ejecutar el archivo de entrada se escribe multiples veces "a es mayor que 10" tambien sucede con la variable "b". Modificar lo que se imprimira con las condiciones evitara esa redundancia.

Jose Andres Morales Calderon - 201602754

**Comment by rjanixz** [comment]
Excelente observación @HPecene, no olvides realizar el pull request con los cambios de código respectivos

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte José.

Saludos cordiales.
