### ISSUE TITLE
Mejora: gráfica del AST

### ISSUE THREAD

**Issue by jeannirasic** [ericknavarro/InterpreteSencilloIronyCS#6]
Se implementó una clase llamada "controlDOT" la cual contiene métodos para graficar y mostrar la imagen del AST. Los métodos de esta clase son llamados en el método "analizar" de la clase "sintactico.cs".

Jeannira Del Rosario Sic Menéndez - 201602434

**Comment by rjanixz** [comment]
pull requeste de este issue: https://github.com/ericknavarro/InterpreteSencilloIronyCS/pull/7

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte Jeannira!
