### ISSUE TITLE
Errores Sintácticos

### ISSUE THREAD

**Issue by sergiozapeta** [ericknavarro/InterpreteSencilloIronyCS#9]
Mostrar en pantalla los errores sintácticos y el lugar en donde ocurren.

**Comment by rjanixz** [comment]
PR: https://github.com/ericknavarro/InterpreteSencilloIronyCS/pull/10

**Comment by ericknavarro** [comment]
Muchas gracias por tu aporte Sergio, muy claro el cambio y muy beneficioso para el proyecto.
Saludos cordiales.
